export const warehouseTransferHistoryRecords = [
  {
    transferNo: 'TRF-20260506-0001',
    fromWarehouseCode: 'WH-ICN-01',
    fromWarehouseName: '인천 제1창고',
    toWarehouseCode: 'WH-BSN-01',
    toWarehouseName: '부산 물류창고',
    requestedBy: '김본사',
    requestedAt: '2026-05-06 09:42',
    status: '완료',
    lines: [
      {
        skuCode: 'PRD-TOP-SH-003-NVY-L',
        itemCode: 'PRD-TOP-SH-003',
        itemName: '오버핏 옥스포드 셔츠',
        color: 'NVY',
        size: 'L',
        qty: 24,
        reason: '재고 불균형 해소',
        memo: '부산권 셔츠 재고 부족 대응',
        fromStockBefore: 58,
        toStockBefore: 8,
      },
      {
        skuCode: 'PRD-TOP-SS-001-WHT-M',
        itemCode: 'PRD-TOP-SS-001',
        itemName: '코튼 베이직 반팔 티셔츠',
        color: 'WHT',
        size: 'M',
        qty: 18,
        reason: '재고 불균형 해소',
        memo: '동일 노선 장바구니 병합 처리',
        fromStockBefore: 92,
        toStockBefore: 16,
      },
    ],
  },
  {
    transferNo: 'TRF-20260505-0003',
    fromWarehouseCode: 'WH-ICN-01',
    fromWarehouseName: '인천 제1창고',
    toWarehouseCode: 'WH-DJN-01',
    toWarehouseName: '대전 허브창고',
    requestedBy: '박운영',
    requestedAt: '2026-05-05 14:20',
    status: '진행중',
    lines: [
      {
        skuCode: 'PRD-OUT-PD-001-NVY-XL',
        itemCode: 'PRD-OUT-PD-001',
        itemName: '라이트 숏 패딩',
        color: 'NVY',
        size: 'XL',
        qty: 18,
        reason: '프로모션 대응',
        memo: '1차 이동 후 반응 보고 추가 출고 예정',
        fromStockBefore: 56,
        toStockBefore: 5,
      },
      {
        skuCode: 'PRD-OUT-HZ-003-GRY-L',
        itemCode: 'PRD-OUT-HZ-003',
        itemName: '트랙라인 코튼 집업 후디',
        color: 'GRY',
        size: 'L',
        qty: 12,
        reason: '프로모션 대응',
        memo: '후디 수요 급증으로 선이동',
        fromStockBefore: 40,
        toStockBefore: 9,
      },
    ],
  },
  {
    transferNo: 'TRF-20260504-0007',
    fromWarehouseCode: 'WH-DJN-01',
    fromWarehouseName: '대전 허브창고',
    toWarehouseCode: 'WH-ICN-01',
    toWarehouseName: '인천 제1창고',
    requestedBy: '최관리',
    requestedAt: '2026-05-04 16:32',
    status: '취소',
    lines: [
      {
        skuCode: 'PRD-PNT-ST-002-GRY-M',
        itemCode: 'PRD-PNT-ST-002',
        itemName: '이지 밴딩 하프 팬츠',
        color: 'GRY',
        size: 'M',
        qty: 12,
        reason: '재고 불균형 해소',
        memo: '출발지 긴급 출고 우선순위 변경으로 취소',
        fromStockBefore: 33,
        toStockBefore: 45,
      },
    ],
  },
  {
    transferNo: 'TRF-20260504-0011',
    fromWarehouseCode: 'WH-BSN-01',
    fromWarehouseName: '부산 물류창고',
    toWarehouseCode: 'WH-DJN-01',
    toWarehouseName: '대전 허브창고',
    requestedBy: '이재고',
    requestedAt: '2026-05-04 18:10',
    status: '완료',
    lines: [
      {
        skuCode: 'PRD-TOP-LS-002-BLK-M',
        itemCode: 'PRD-TOP-LS-002',
        itemName: '라이트 모달 롱슬리브',
        color: 'BLK',
        size: 'M',
        qty: 10,
        reason: '품절 예방',
        memo: '이커머스 피크 대비 안전재고 확보',
        fromStockBefore: 37,
        toStockBefore: 14,
      },
      {
        skuCode: 'PRD-TOP-KN-003-NVY-L',
        itemCode: 'PRD-TOP-KN-003',
        itemName: '에센셜 립 조직 니트',
        color: 'NVY',
        size: 'L',
        qty: 9,
        reason: '품절 예방',
        memo: '같은 장바구니 실행, 다른 노선 별도 생성건',
        fromStockBefore: 31,
        toStockBefore: 11,
      },
    ],
  },
]

export function getTransferSummaryRows(records = warehouseTransferHistoryRecords) {
  return records.map((record) => ({
    ...record,
    skuCount: record.lines.length,
    totalQty: record.lines.reduce((sum, line) => sum + Number(line.qty || 0), 0),
    reasonCount: new Set(record.lines.map((line) => (line.reason || '').trim()).filter(Boolean)).size,
    memoCount: record.lines.filter((line) => (line.memo || '').trim().length > 0).length,
  }))
}
