apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name www.stockit.kro.kr stockit.kro.kr;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }